### ISSUE TITLE
DevOps design

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#100]
## Description
As a developer I want to have an overview of the repos in use within the project as well as what builds get deployed where / what dependencies exist so that I can be effective in development.

How do we support effective development? e.g. deployment environment per developer?

## Acceptance criteria

- [ ] List of top level repositories and dependencies between them
- [ ] Cloud resources to be used for builds + releases
- [ ] Types of deployment environments supported e.g. Dev, Test, Prod

**Comment by GhostOnTheFiber** [comment]
I think that this is a very interesting and appropriate topic that might need to be encompassed into a wider discussion about the tech. 

Some of my initial thoughts:
- Think that having a place to describe the repositories and dependencies is a great idea.
- I think that this might expand into the topic of #101, #63 and #77. Some sub questions: 
  - What platform are we aiming to have this run ontop of: K8s? 
  - Do we want devs to work in docker so that their builds closely resemble prod? 
- I would suggest a Dev and Prod where commits are run through CI for pushes. The CI would have tests run to ensure code quality and functionality. We can look at using github actions for this or look at travisCI.
