### ISSUE TITLE
BUG: SQL error

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1368]
**Describe the bug**
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND activity.type IN ('callout-published','post-created','post-comment','callo' at line 2"

When opening the dashboard page

mentioned by Denise

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Comoque1** [comment]
The issue is reproducible also when:
1. clean db
2. run migrations
3. start service
4. register user
5. Navigate to My dashboard page: `"message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND activity.type IN ('callout-published','post-created','post-comment','callo' at line 2",`
<img width="1332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93bf3af8cdec8d0a4f9e92db1962d244fc329236/image.png" alt="image.png" />

**Comment by me-andre** [comment]
The issue is (was) reproducible only for a fresh user who's not a member of anything yet. Please mention crucial preconditions in the story as that can greatly reduce the time needed to create a fix.
